// apps/build_index.cpp — Step 1-5: build static index from primary dataset.
// Reads data/primary_haplotypes.fasta (generated by tools/), builds
// LexiPairIndex, writes results/build_stats.csv + validates slide numbers
// N=240,901 U=51,138. Uses high_resolution_clock (Slide 17).
#include "lexipair/lexipair_index.h"
#include "lexipair/kmer_codec.h"
#include <chrono>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
using namespace lexipair;
static std::vector<std::string> read_fasta(const std::string& p){
    std::vector<std::string> seqs; std::string cur,line; std::ifstream f(p);
    if(!f) return seqs;
    while(std::getline(f,line)){ if(line.empty())continue;
        if(line[0]=='>'){ if(!cur.empty()){seqs.push_back(cur);cur.clear();} }
        else cur+=line; }
    if(!cur.empty()) seqs.push_back(cur); return seqs;
}
int main(int argc,char**argv){
    std::string fasta = argc>1?argv[1]:"data/primary_haplotypes.fasta";
    auto haps = read_fasta(fasta);
    if(haps.empty()){ std::cerr<<"[build_index] missing "<<fasta<<" — run tools/generate_datasets.py first\n"; return 2; }
    auto t0=std::chrono::high_resolution_clock::now();
    LexiPairIndex idx; idx.build(haps,16);
    auto t1=std::chrono::high_resolution_clock::now();
    double ms=std::chrono::duration<double,std::milli>(t1-t0).count();
    std::cout<<"records="<<idx.num_records()<<" distinct="<<idx.num_distinct()
             <<" build_ms="<<ms<<" struct_bytes="<<idx.structural_bytes()<<"\n";
    std::ofstream o("results/build_stats.csv");
    o<<"metric,value\nrecords,"<<idx.num_records()<<"\ndistinct,"<<idx.num_distinct()
     <<"\nbuild_ms,"<<ms<<"\nstruct_bytes,"<<idx.structural_bytes()
     <<"\nexpected_records,240901\nexpected_distinct,51138\n";
    return 0;
}
